baseurl = "https://www.lyranthe.org/prometheus_client_scala/"
languageCode = "en-us"
title = "Prometheus for Scala"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Gary Coady"
	description = "Prometheus Client for Scala"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/fiadliel/prometheus_client_scala"

	version = "0.5.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "fiadliel"
	github  = "fiadliel"
	email   = "gary@lyranthe.org"


[[menu.main]]
	name   = "Guide"
	url    = "guide/"
	weight = 0

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
